language: php

sudo: false

matrix:
  include:
  - php: 5.3
  - php: 5.5
    env: PROCESS_CODECLIMATE=true
  - php: 5.6
  - php: 7.0
  - php: nightly
  - php: hhvm
    env: IGNORE_XDEBUG=true

  fast_finish: true

  allow_failures:
  - php: nightly

branches:
  only:
    - master
    - stable
    - release
    - staging
    - dev
    - /^(.*\/)?ci-.*$/

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist

script:
  - composer update
  - composer test
  - composer lint

cache:
  directories:
    - $HOME/.composer/cache
notifications:
  slack:
    rooms:
      - crazyfactory:$SLACK_API_KEY#dev-noise
      - crazyfactory:$SLACK_API_KEY#travis
    on_start: always
