language: php

sudo: false

matrix:
  include:
  - php: 5.3
  - php: 5.4
  - php: 5.5
  - php: 5.6
  - php: 7.0
    env: PROCESS_LINT=true
  - php: nightly
  - php: hhvm

  fast_finish: true

  allow_failures:
  - php: nightly
  - php: 7.0

branches:
  only:
    - master
    - stable
    - release
    - staging
    - dev
    - /^(.*\/)?ci-.*$/

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist

script:
  - composer test
  - if [ $? -eq 0 ]; then
      echo "Happy face :)";
    else
      exit 1;
    fi
  - if [ $PROCESS_LINT = true ]; then
      composer lint;
    else
      exit 0;
    fi

cache:
  directories:
    - $HOME/.composer/cache
notifications:
  slack:
    rooms:
      - crazyfactory:$SLACK_API_KEY#dev-noise
      - crazyfactory:$SLACK_API_KEY#travis
    on_start: always
